# Generated by Django 3.1.5 on 2021-01-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('stu_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_psw', models.CharField(max_length=20)),
            ],
        ),
    ]
